# Generated by Django 4.1.2 on 2022-10-25 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino_PainelDashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendendor',
            new_name='Vendedor',
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 10, 25, 14, 39, 56, 695636)),
        ),
    ]
