# Generated by Django 4.1.2 on 2022-10-25 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino_PainelDashboard', '0002_rename_vendendor_vendedor_alter_vendas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 10, 25, 14, 53, 6, 429065)),
        ),
    ]
