# Generated by Django 4.1.2 on 2022-10-26 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino_PainelDashboard', '0003_alter_produto_nome_alter_vendas_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='despesa',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 10, 26, 13, 24, 10, 863774)),
        ),
    ]
