# Generated by Django 4.1.2 on 2022-10-26 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino_PainelDashboard', '0004_vendedor_despesa_alter_vendas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 10, 26, 13, 36, 44, 989744)),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='despesa',
            field=models.FloatField(default=-1000),
        ),
    ]
